<?php

namespace TT\memberBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolsRepository extends EntityRepository
{
}
